apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-violin-deployment
  labels:
    app.kubernetes.io/name: go-violin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-violin
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-violin
    spec:
      containers:
        - name: go-violin
          image: registry.hub.docker.com/khaledemaradev/go-violin:43
          env:
            - name: PORT
              value: "7090"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 7090
      imagePullSecrets:
        - name: regcred
