apiVersion: v1
kind: Service
metadata:
  name: go-violin-service
  labels:
    app.kubernetes.io/name: go-violin
spec:
  type: LoadBalancer
  ports:
    - port: 7090
  selector:
    app.kubernetes.io/name: go-violin
